name: Run push.py every 6 hours

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yt-dlp

      - name: Add cookies file
        run: echo "${{ secrets.YOUTUBE_COOKIES }}" > cookies.txt
        env:
          YOUTUBE_COOKIES: ${{ secrets.YOUTUBE_COOKIES }}

      - name: Run push.py
        run: python push.py

      - name: Commit and push changes
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add lives.m3u8 Hhshs/TV-FIX.m3u || true
          git commit -m "Atualiza lives.m3u8 e Hhshs/TV-FIX.m3u" || true
          git push https://x-access-token:${{ secrets.REPO_TOKEN }}@github.com/Walter-Henri/Hhshs.git HEAD:main || true
