name: Run push.py every 6 hours

on:
  schedule:
    - cron: "0 */6 * * *"  # Executa a cada 6 horas (UTC: meia-noite, 6h, 12h, 18h)
  workflow_dispatch:       # Permite execução manual via interface do GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest  # Usa a versão mais recente do Ubuntu disponível no GitHub Actions
    steps:
      ##########################################
      # Checkout do repositório                #
      ##########################################
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main          # Força checkout do branch 'main'
          fetch-depth: 0     # Baixa todo o histórico para permitir git pull e commits

      ##########################################
      # Ajusta permissões do push.py           #
      ##########################################
      - name: Set executable permissions
        run: |
          echo "🔧 Ajustando permissões do push.py..."
          sudo chmod +x push.py || { echo "❌ Erro: push.py não encontrado!"; exit 1; }
          echo "✅ Permissões ajustadas com sucesso."

      ##########################################
      # Configura Python 3.11                  #
      ##########################################
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"  # Define explicitamente Python 3.11
        continue-on-error: false  # Para o workflow se a configuração falhar

      ##########################################
      # Instala dependências do sistema        #
      ##########################################
      - name: Install system dependencies
        run: |
          echo "🔧 Atualizando lista de pacotes do sistema..."
          sudo apt-get update -y || { echo "❌ Falha ao atualizar pacotes!"; exit 1; }
          
          echo "🔧 Instalando ffmpeg..."
          sudo apt-get install -y ffmpeg || { echo "❌ Falha ao instalar ffmpeg!"; exit 1; }
          
          echo "✅ Dependências do sistema instaladas com sucesso!"

      ##########################################
      # Instala dependências Python            #
      ##########################################
      - name: Install Python dependencies
        run: |
          echo "🔧 Atualizando pip para Python 3.11..."
          python3 -m pip install --upgrade pip || { echo "❌ Falha ao atualizar pip!"; exit 1; }
          
          echo "🔧 Instalando yt-dlp>=2025.02.19..."
          python3 -m pip install "yt-dlp>=2025.02.19" || { echo "❌ Falha ao instalar yt-dlp!"; exit 1; }
          
          echo "✅ Dependências Python instaladas com sucesso!"

      ##########################################
      # Executa o script push.py               #
      ##########################################
      - name: Run push.py
        run: |
          echo "🚀 Executando push.py com Python 3.11..."
          python3 push.py || { echo "❌ Erro ao executar push.py!"; exit 1; }
          echo "✅ push.py executado com sucesso!"

      ##########################################
      # Commit e push das mudanças             #
      ##########################################
      - name: Commit and push changes
        run: |
          echo "🔧 Configurando identidade do Git..."
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          
          echo "🔧 Sincronizando com o repositório remoto..."
          git pull --rebase origin main || true  # Ignora falhas se já estiver atualizado
          
          echo "🔧 Adicionando arquivos ao staging..."
          git add lives.m3u8 Hhshs/TV-FIX.m3u || true  # Ignora se os arquivos não existirem
          
          echo "🔧 Verificando mudanças para commit..."
          if git diff --staged --quiet; then
            echo "ℹ️ Nenhuma mudança para commitar."
          else
            echo "🔧 Fazendo commit das mudanças..."
            git commit -m "Atualiza playlists lives.m3u8 e TV-FIX.m3u [automático]" || { echo "❌ Erro ao fazer commit!"; exit 1; }
            
            echo "🔧 Enviando mudanças para o repositório..."
            git push https://${{ secrets.REPO_TOKEN }}@github.com/Walter-Henri/Hhshs.git HEAD:main || {
              echo "⚠️ Push falhou, tentando forçar..."
              git push --force https://${{ secrets.REPO_TOKEN }}@github.com/Walter-Henri/Hhshs.git HEAD:main || {
                echo "❌ Erro ao fazer push mesmo com força!"; exit 1;
              }
            }
            echo "✅ Mudanças enviadas com sucesso!"
          fi
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}  # Token de autenticação para o repositório