name: Run push.py every 6 hours

on:
  schedule:
    - cron: "0 */6 * * *"  # Executa a cada 6 horas (UTC)
  workflow_dispatch:       # Permite execução manual

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0  # Permite histórico completo para git pull

      ##########################################
      # Novo passo: Ajustar permissões com sudo #
      ##########################################
      - name: Set executable permissions
        run: |
          echo "🔧 Ajustando permissões de arquivos..."
          sudo chmod +x *  # Torna todos os arquivos executáveis

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      ####################################################
      # Atualizado: Adicionado 'sudo' nas dependências  #
      ####################################################
      - name: Install system dependencies
        run: |
          echo "🔧 Instalando dependências do sistema..."
          sudo apt-get update -y
          sudo apt-get install -y \
            libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libgbm1 \
            libasound2t64 libx11-xcb1 libxcomposite1 libxcursor1 \
            libxdamage1 libxi6 libxtst6

      - name: Run setup_and_run.py
        run: |
          echo "🚀 Executando setup_and_run.py..."
          python3 setup_and_run.py || { echo "❌ Erro ao executar script"; exit 1; }
        env:
          CI: true  # Sinaliza ambiente CI para o script

      - name: Commit and push changes
        run: |
          echo "	Configurando Git..."
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          
          echo "	Pull para sincronizar..."
          git pull --rebase origin main || true
          
          echo "	Adicionando alterações..."
          git add lives.m3u8 Hhshs/TV-FIX.m3u || true
          
          echo "	Fazendo commit..."
          git commit -m "Atualiza playlists [automático]" || true
          
          echo "	Push para origin..."
          git push https://${{ secrets.REPO_TOKEN }}@github.com/Walter-Henri/Hhshs.git HEAD:main || {
            echo "	Tentando forçar push..."
            git push --force https://${{ secrets.REPO_TOKEN }}@github.com/Walter-Henri/Hhshs.git HEAD:main
          }
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}