name: Run push.py every 6 hours

on:
  schedule:
    - cron: '0 */6 * * *'  # Executa a cada 6 horas
  workflow_dispatch:  # Permite execução manual

jobs:
  run-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Run setup_and_run.py
        run: |
          echo "Executando setup_and_run.py para instalar dependências e rodar push.py..."
          python3 setup_and_run.py || { echo "Erro ao executar setup_and_run.py"; exit 1; }
          echo "setup_and_run.py executado com sucesso."