name: Run push.py every 6 hours

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Garante que todo o histórico do repositório seja baixado

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yt-dlp

      - name: Add cookies file
        run: echo "${{ secrets.YOUTUBE_COOKIES }}" > cookies.txt
        env:
          YOUTUBE_COOKIES: ${{ secrets.YOUTUBE_COOKIES }}

      - name: Run push.py
        run: python push.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          
          # Garante que temos a versão mais recente do repositório
          git pull origin main --rebase || true
          
          # Adiciona arquivos ao commit
          git add lives.m3u8 Hhshs/TV-FIX.m3u || true
          
          # Faz o commit, mas não falha se não houver mudanças
          git commit -m "Atualiza lives.m3u8 e Hhshs/TV-FIX.m3u" || true
          
          # Tenta fazer push normalmente; se falhar, força o push
          git push https://${{ secrets.REPO_TOKEN }}@github.com/Walter-Henri/Hhshs.git HEAD:main || git push --force https://${{ secrets.REPO_TOKEN }}@github.com/Walter-Henri/Hhshs.git HEAD:main
